apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argo-rollouts
spec:
  encryptedData:
    .dockerconfigjson: AgCYFMDsZozfB18x6Krz65DMCgZV9caKD8Ovx7T3fJ8RZg+kOkHfRGUO4VPwMTggkPtl0UjShdVZEo2A+GdGXRr2f3EL+ufq+9p1BWP+3nVswZW740L0CgMB1GnsZsUWGjCaTsY5gmKPj51h7k0Z0/fIefrBEMEN1Wkp1JQD4JIs/xvUAL/TVmShAwUyqfadq4KEYFhwSEjCmYWuRkuCdDT0JCPw/QfO+yZYJFkSTlIBRSFDX2eyGUiKjnI1WrAs0J5HbFwrKpoZsarDfvGuzDsaPtwDtUoSfv8rXChb+xuPPeAT1t97yGuyTqUYHsAbyr/IZOU+OxRoNptx1MWB1nj5hDinQC4kT16abeWZUYnbJ8NI80C6d93TmPbn9I/cmBSBhnmMfdt3tiU2tO8PUhYE0tnktFMkbTuBLaMrBDvzZ19C01cdPyMK5p/tXjt9lGbG8tg8Fpwchl0/lq0wNSnX+XGyVsMm21Jxd9jUEzpCelnYUtLvaOtmFuntESgO9Et5UoscCDqWbJ1L4C05tSuO6CVh9pm5YgWTdGZWK0JzfqaJmVwMTD+Hn8dZEa6Orryn0PmpLZ5MkmSdREyguWVw+W7MQQwxH+PNX6NDUh+v5UxHEAfS3BF77U+3VGh8kFuSzRu/aB+3dTNwIxo9AelreFL8sQm5A17kB0XNMG9vztOP/2SAuVWC10AYyjtdMPfV85gCRRu8fjVvh+IjIBkXDl9B6Wgei7xMB/mzqQiqKkKk4DyDOqZEMcnRJi63Ey5rcfswi5BzLzul4SUKkIY1bwKLxZeiNorn+grN6kFpo0uVGeFlElrVd1+RKEwOOOLVm9BqUa7gJG3T26SPqIRzpTSIlyrmjmw+G+G+txkXPquJrYCcM+KF1vf7cDgx+82EKvzb+PAec2yB0YZ/c+7sizE9cBcztai+0bDZCwEXVgOM8+rEV7tfyuivDKvNW7OgN2uAoJOJy20CDNFjGcrr20aPmN132fQBEGt5BtY5RBT57ns=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argo-rollouts
    type: kubernetes.io/dockerconfigjson

