apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argo-rollouts
spec:
  encryptedData:
    .dockerconfigjson: AgADa00yFi+WfKFgzCj+rjX7R1GB4kOFqYRqJN69w6cdQXNyyIj2G/xrUdrrXmycpgXicQ8HyI52yjn84EC+UeYr/LZP1U26sJjCc2umrAmFf9NdMUitMwXFDYntImdstMjhj5IBqX4HOUWQMP/Nb3LeZA0CGNQzNUhIDR8koxrVwNgqB49xGTs9NVcGZVln13DhZjZgCJ6oC5LQNcRd65XJ6wLuG0KgpclF11Wx7USh2BeTYvKnBgv6g3MEnJRJv/Ikw6VT9e4xLthFNfsRvT/0pxtsLySC8qUqAuon1u5s1aDjIcVljp5fl3ImN3KgYj9e13TBeBwE0tvH1SIDG7L94ZDLqAZJnYuGUmmAwRWLxvBlkqIzZ3Mte8FpkEs+TKJcwfj5wg9jHi6K2Y1rfEzy9oHmIf9R5N6zxRPlsF2+5jrqkP1tEpZpBWlFzPBdXAKwREwGOf0y4ZRH9x3ylyx5pEa+lz1GRtw9njWEcpkysA3kKyanqbradPZFn//B4Kp7N4H+O3KZQLhjuRkIvYP3C5byRvIX1BlpC63J72NfL8R5TVqpxp1dIR4G/dFYF4PGN4ChjWeZNpNpZR/L9Nz5EE2+99IMekQkH0cald9ums9dqx1o3cqx+l0kwdiHnP0sgVfhqGqYGAYVF8RAN/5X0H6SK3rDFNZhJpIs9VPCjvUzyDNHw0TOpXdN+ARSIF926NILpi1tvd01WOGy8gukP34NDDySGXM9fYlO68hPvI5/mvKFQO+5PEeNZP31/m9VgJCOtUMm2y7HXGp+ryDpR3UWtoTSVEerdaA+BifTZoobq8HALHHH1QaAVAEDq2b8f0H+7kL899JKBfKEfX/mHnFkvPu2Wo1zy817SvQOg3cjhrxYpTS8AwynrOTY3td+xC3isxz7U+kIyYmaALY+z6d9z4WPcyyNmc8gDVtRaWnUnHr+EbZIyaV6MUtn+NLScvup1miN5i44NIcQTbvEJlpixgqlw20omRIZvKFmOU2+paE=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argo-rollouts
    type: kubernetes.io/dockerconfigjson

