apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../workflows
- regcred.yaml
- ingress.yaml
patchesStrategicMerge:
- argo-server-role.yaml
# - argo-server-deployment.yaml
# - workflow-controller-deployment.yaml
