apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBorV0Fe+GO1ApIZm+UwlJHase7ezb73uDiAuc65SXQaLlFA0i4bbUpvv3yLLymykukll2DC0BJPmY8f1FaMITRyI6MZHV/gbQESyBfkvmFb5srKbxBbs2eQQDhCYxHJ6zHznZiU9B3GvMpZK9NY2+4GteySWcnXv1KgLpCkX9IRvatttI/AMC4GbNqS6SKLNBni9wtFf4EiYH7pFUnHE7L0+0QKpQUZI5Bo/56+xtfhDSPGpM53ITOBFolJQMEZKIcB5cQwNUW6lGcRb5rLZUdv0SSchB1d2JTGmg0u2msaWptV6IAI+BsxLS93B2yET0nE20YfaQ9yW9veebWjQYCrJZb1On7IT5OV9bxoY+IswBanvdLvheUEKvRDtUSGhj7iD/RB3aHQrSYiQf37qCGaKwD2O4Eh9KQ1dM25WM7GrEV5WN+ihKIuAwOM39ioweXkuzjs5LR+XnoYwzChMALrxx6U8tTXFbYqP1gSNfpAepImirc5Ubz3CXD/0FNYqGnLsdYRl6RWNlFeNNojC3y222u6pOkfOr0fbe/sHGsVE5lpOdaGtWycXmndK0nA7L94H/PoubCV3ADtHLw1/dM79d2QTqbvZG8XRValXb0wtp1g/rir6POrPdEMsQlhcVsivijTGM+T6YltzG24bVoMFjf5OUJXaRsr/umdwqcni7Gn4PDC/PNxz1avPvUPvujyLDA3dRA5eTzW+/1Aldsq2sxBpQavra8j5iuH31pJl/NIHg5W1ENwDfuksZa1EM6nBqgmQlQbuJonygxY9sOemWvxj6lb4KO9j28Wnv32fsBa8O7ufNQeog1WnK9kG9BqzpSM0Zn7Dp0ZjbN91t1XyHFQUeWX/sUJ/CvATW3TFx5Grzbx6Xzgs71KljHQZprAaNfpy6HlbFs2ljHDtu+yP1ywthG
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

