apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
spec:
  template:
    spec:
      imagePullSecrets:
      - name: regcred
      initContainers:
      - name: copyutil
        image: quay.io/argoproj/argocd:v2.6.7
        env:
          - name: TZ
            value: Europe/Madrid
      containers:
      - name: dex
        image: dexidp/dex:v2.35.3
