apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgAbgYhWb0ocZINu+i93jrZAnXROmqrchVKvR2ep/pJKf15izn/VqAnYJPxtDZ8TPXpWHM6Dn2Bt+nuo40FAnNEN7Pe+vnFjvsVwL2ygF8vrtb9XRAlKJc0L5y746RQjSYSfNON1CPMUHYr8dAo3nz/bJVoxLYxWLLR9eTtTAzo4pBErPuNrC1mLUqEVHqGeel1UzafQ00llXAdqez7PofD5aEIz/acD0W6apZ6yRbHf5V14cu9Axr5Fm3etZ0qtDiuwKP5XdqIfpB9fY2/brCzWrsiVeSJJaKpeAlYNmNOPuw4NcWrdAWscyHMUWYOkWeF8GQEs/i7X6aOR2stSrCeoBkg5qw6jffx7XApal1Fe78c1g2iEtp/oAfj3PnpND2vVifyR0oOpZtRm4+jk5Ze6bUSIQjjdChqgMqHsxAUppsXCpZh5iNSGFRJGg5PGpFmtlSalf1ACTGufcFbrFDKu2FzVvYcbTLm91/tFGLTjVDMx9KX3/fDf9UA1X+rp4XM/5GY8+1UzSPeLWWAwuGONX57JKzSQa1R3OlLd0LOvSbl2ljBH9pec/x8L4lRWhhjLTmDzHWUGTlqYv/RLfUwqgQg887FM7cXUFknj92EMpAIpFkDh2osXXLyIXW2/ufcoHUIRJm1Kh3K9xHASBbAo5DT5Le3bGyfjO6EaFKxpnmAjqHIR6bQQAQVScETHy9VCz6eL/alacRv1cMK2VwMoyJvNw+8/F3M/OoqvGa+trxrg1TlchcwSGQpNat4rSqtrnpcmvZhvuraJtLdTj45FPXmx+yk11t24LK8zcejK85fZaz2CuRH7ibvnC6u5+dhSW4RiswTy0zuN0UkMXG770lTvu+Gw58beHAmjpGR5UV7rQHTmzXeeqqJY/skscDveJlcw6gssHSE5hBlIi5pmZWHVeVx8
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argocd
    type: kubernetes.io/dockerconfigjson

