apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgBhn8se6v8zJrPUqlVoyk34HD9nSPhHXZLQvG+PwqLNuyjZc1XqXexYHsZ2iYBqS2MSiC8zVmuzZo0Z3tZyj/XKT0bV7hHrs69JSN/Opd4gbzSsLw70360+Lm9w1IUc1NCojyacTRzL++2iExpN7NKYJC7lQQOuDlFnzom5+7OFLZ7hBovrMq7EVXd9YVPxlm95K+3dwHvLRoK1w2u/ImYugOxcrDMraX5CISQdJzkSfyEmwtwi/Ga+rKEdxgkCYLlQeYg1OhBMyjnFrM6UePtOk/nl5FWgFlwXdY2vdFPGpd2KNkkSrYDNDDhpCyKQLxgyZu2scENX06li47oC47+7p8HrnovHGApRtN1b6bmswmN6M7oxVlUHwO3ziLB/reAXfcL1RkODxtpJEQ7oYn+qfaHOTcUHVLRJbnTN25za8BvThAOOc0Doh9lJrSFOqRryv99ouco9vpO4d/uN1C6T/vnPo92kPCYvbmL63EDD0FZ2a+c2l1G2qtAyTUnsu2LDWFWCTYU8BbPD/hJniLrzmgKxjZOsM7fXaD0q3s210OYYdT+LlW/5+oXV4VjsH/Cfoya+Z3bb0EgqKVADc2wC/wPeMRfvzL8MIa1aRx6NG+2FqiLtEC3dTS3Ksgqb+OksUdHypBPv8tepxpaLJIuBqvVL5l+5XNlISQbqhiGl7MxdspkuoX8hKhZAphKRf6lBdX7xaXOqXOlOFNupFlapuIMirmu1Td2eNSHCnpJMJmd3HWtpxXFeHn1mHBcM5JyKV+bWf8lneK5AO/N20Z3HUgPG5/doGJCBlWXbc4Wk+ec5+/TTC3Oyb/bFKJKFsGtIi6euHoAmtVC6om7/qLpudw8nIDs30+ZjqBiAUsGCVqMSXDegBg000a15/9EXIUqbKBqfcb/2u/81vasvajvwfsTzc71BNep4phsAtJMPCx4W3kouutNTcv14UoF2AjNR8CwdFVoT90Oly3AwOJbVCPWGmrNpDBsnShGp17xaf3iif8w=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argocd
    type: kubernetes.io/dockerconfigjson

