apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgAAzhAHKkpWzvh8EPreRaxVtacFWCYsjT86zwOBTJ+IkBHp5LsT/iQ8rcRQ7IOtYTlC3WqNDKBFhuD1tyB6KhYlqpTWG2cVet/poal+CsLNsuBpHlJW4myjdLChsXrKbLZRBlZ+pl0K6kqbdheE6vcyHNGgw9iKD7BkFE4ow3wkU47ljEaQEzDzC/YFiZJ/Xzg1kcoJ1u82R7kw3eMWKzLcB39DJTOvOHywdo9UQXNv0G+Hwzv/lv5vH/W1daRVrCvTh/wEKahNG1yXtjXw4sS22lrvmN+PSrzQCqBf74D9GK5pS3o/CsMqAtzrlkdA0JpQxG+6nVc9cqTSpD3obRShXh6osDoENwsgZvFkcKU6JzfCOA8FoKbGrP2tTmbDL7VJsQdqctgyvQU9GJXCTfnZ12rUKE4pOicsDhblIdgCJs1Af/l+KeL4YUQsboSW4hdijOLtF7MV3NON39flYQeaB7CR5PdLwelODqCfIRBrVZmtMPKSZqkStX0JudUGNnkYgIH4DISNt+xGGg1L6FJk8tXmiKpw5U/qM/OAVy2cPXPFCJ5XQSRQriQTLJJlGYt/72S6JVr2Dhp0kVGg8iKt9qEUc+Q26Khlvry/XUrZbq0zGklDPSU3v/ZtT+Vj/9BiXC4QQL0xNJp4etk/qBjP9uAFUXUwzZ4JDsa+YpwsRwbLvl2WC5EQThK5fcdvb6iDjB7Tz1Vxw9poA53CWUoUp/tiM0cm1G5n00mFZLuAjn7RIdbwTHPkD4KsRbkr7Ux++LusrX/fRD3GiiYHD6JEKGbtWYLAsEFy12JlwwgLSOEARB8Vkbs2OkqiGJDzQ0AztfeJbVIO10b1aSYeT4NZT1EaqdFXeZ0sOilF1izD8Eo+2eyqijXnuqRzNl9YtOzwbx8OO4w8iSEei60u+KTEMswEuAjePmLvodIm7iAaZoyMX5NoVM1vC/elYOtVPGhlXBoEXOOEMQ7xAZMVo88zaYZ1FepFEIA72SklOtM=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argocd
    type: kubernetes.io/dockerconfigjson

