apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgAjmFkUXVrp6ZEHVQ4jXP8MtHBoaMNtVnyx1YnJOWKgd5QHY8aDc9XCkSu6DXnq/mX/X4G+EjzmOLBDj6Ng+ytbQGQMlyg8PcobkBxXm2yYZo6ESvR/LjjBzyqq/Imqg8nuvukmV4T8Fe+EZ/o9b/SQDOurmlvnckeRQvmpf6biivSeIK6gK8dSwq3FHrnjsiSzDY4ZkafN9pGX3bYTlF+4gdM/A5CGsXttoM9rhLaaxPNqwse/vqECIKcD5YBNV++4oZLGaVxqvZGvgT6BqiKPyS61VmWFZ1kfZxKlXj4wkgV655vr4AykJzGUVsdXMl6gSEzn1UEsHvM24Yv8RsBY8SvX8wdSvxDbH+peHt4uJRwVZGcgMvi6+uENimlbivWgH2ufjFxtIeE+ArJH5o3i1Mc+uRhHhUDRUDe9XpL4g/rMpJm75ySUDiO+V3lT3wt0edkfrjuVgixIzcOcKVIXSXhjnxB90mIfvE26DAMzNcVOEq75u+yvxQGhx96CBPQChcG5SltAQiFK0w3ZaEO6lJDb8Tlby/z68/83oDF3M9s9zmzadZsCuVzTT64dkSRI65hdv/2caRapHJYUci3wNLf0dEfxy/16ZoLvwLrneoH2ZAcDH6j/7fipS76BHLJ+f+20BTyez1w7mEXKiAjD726MBL/55WTIjjLnyMD/UOtYm4uRSEZaP55EgPVR3qJWWlrno53T3IadAjBc8MnnNKyw2iUWQWJwFnMtz+Y0JRHs/X6z8tB52dJGELE90DiwMVELsncHCkgJakEL3jHZVKB5HFJq/kNcamjyOkAx0Uj6JVva/FVnZH9l46O7B+oCRiRcTzsE46PJwXRXLAzCSegKBiU7oMXjtrNxRf0LkxrJwWKJ6WAFOC8fqRS8mUU8fFidpk+zR+vjY2P8VlDrnFfxKZTJ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: argocd
    type: kubernetes.io/dockerconfigjson

