apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: production
  source:
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: "true"
        - name: extraArgs
          value: "{--dns01-recursive-nameservers=1.1.1.1:53}"
    repoURL: https://charts.jetstack.io
    targetRevision: v1.8.0
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

