apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: ./
    repoURL: https://github.com/alborotogarcia/helm-kafka
    targetRevision: master
  destination:
    namespace: cp
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
