apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: manifests/charts/istio-control/istio-discovery
    repoURL: https://github.com/alvarogg777/istio.git
    targetRevision: 1.10.1-patch
    # helm:
    #   parameters:
    #   - name: global.hub
    #     value: docker.io/querycapistio
    #   - name: global.tag
    #     value: 1.9.4
    #   - name: global.defaultNodeSelector
    #     value:
    #       kubernetes.io/arch: arm64
    #   - name: global.arch
    #     value:
    #       arm64: 2
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jsonPointers:
    - /webhooks
