apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: storage
    server: https://kubernetes.default.svc
  project: production
  source:
    chart: minio
    helm:
      valueFiles:
        - https://${GH_TOKEN}@raw.githubusercontent.com/alvarogg777/minio/main/minio-values.yaml
    repoURL: https://charts.min.io/
    targetRevision: 4.0.15
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

