apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: helm/manifests
    repoURL: https://github.com/alvarogg777/BentoML
    targetRevision: patch-0.12.1
  destination:
    namespace: ml
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    #syncOptions:
    #- CreateNamespace=true
