apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: chart
    repoURL: https://github.com/rancher/rancher.git
    targetRevision: master
    helm:
      parameters:
        - name: hostname
          value: rancher.example.com
        #- name: ingress.extraAnnotations
        #  value: 
        #    - kubernetes.io/ingress.class: nginx
  destination:
    namespace: cattle-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
