apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yatai
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: helm/YataiService
    repoURL: https://github.com/bentoml/BentoML
    targetRevision: master
    helm:
      parameters:
      - name: yatai.image.repo
        value: alvarogg777/yatai-service
      - name: yatai.image.version
        value: 0.12.1
      - name: service.type
        value: ClusterIP
  destination:
    namespace: ml-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
