apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-rollouts
spec:
  template:
    spec:
      containers:
        - name: argo-rollouts
          image: quay.io/argoproj/argo-rollouts:v1.4.1
          env:
            - name: TZ
              value: Europe/Madrid

