apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgDDocSIhDeWM3iSXPzhkhyQaRMxKWMOra+i402BAY0XzS6AYtJWB6EoIwexzShMy1Yy7OyN6GWenExejo1XG6GrwSRUvweMRN51oAAnIBZlM+LrY9W8eFYDqHErcxjpz8uMWI5XsMVL8sIQ0uC0Bo2FLeu+RwoslLN5ey+g/a0PKcHnUkd8sVpDxLUuIHHoDafOyrlmZKewZtj7rkExMmSnnA9mTT/0T3SBB/IgsBkVP+B0bryCRZKwzjmV8lBXx77IV7OSRvkyEwuQ6Z6LW3KaLnOQ5zm9KVzBSyg/OBtW9p+bQbgTFSTU7NgjzTajt7gZ8555iJxj49dYC0oVFFP046aDLYKzRFqB6C7Zyg2NlKw9kg/IYlUp2QX0wwQ6SC1SeWPiTA9ipV7bwEYr7Csf/l1Om4Y/uMdzrciHSrFZYU8nB1tGbXIpwOAo3ljAig6eGq9GoZhm4unioGIaYH6LWbSgTuyZNTteedIJ7gzBy4M1NOP+JfQTMw0PfqxQ02XPJ+Nmz5Ls8p0+PeIbjL8b8CKZv5rPF3gW4ex0LopPmI0BA3kJ0tNYHINPOkjaD7T0ZWTW869WOY9uPCTT889d7oGvtt6IfC1TCwMDjYsXp1T1ePB1GPC5DTfadixqz/6zYrHX/LRFkfUK9ZfdB8Xzf9eRN4hTaSnKJfjOKHmEhtoJ31xr+dtrmGxwvXVRUGmjDPq1CrC1Y1ZhHeQzXW7GaOlyHp1/hR4Vrq/uh22eXkgZsz9wAv/b
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

