apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgADVkHCUoiqM9K/ggj79UlG9ziOBSubtcZJU7uP6g3FOYpu/nOY9WLz5yyfe9M0ZpObtRcCmuvxSJxp3UI1aN5Lx6TDQViwhQ5r8zyBOmw1rMXJz5+J6H1MsYMrHpWcT7AzIRYIlM6tFqoNtdxY4DaP9E2KLDCkPRrPVTHi5yiOSkkMr+/5AEZnkmQaSDBYfVyuHTg0NsBV+GYsSmPH9k3dR7RVqmntIBS3gem8X2QpUtq9B2AgGOl0Y9eT3mUMzOESgHgbXn+HhIjm3QVo786a0pjwEkE/JIljRId3JMUHjx2qcSjr8BQTDDnY7Zsh15KOnmK8KqCgsHNNT3x7hJ1c3XyzY43kt1UBxdLJwVE34wDAI5/mOcGWmXF273EEczDixzXh76MhvYJAlCbcRIECdns7eMGhBCNwcfq7HvhALB79XcmvPf/OJFx8+9SpQ0CafLVtTnpzxag8nJteb3TG+ybqD/ukOji2a5GCGYgoZ6/ObcJNt+O8iPuAsM1NGIgBUZ5WUctTuMkndFJ95wsSDo8MHcxVdylawGGnG/ka5D7nnRnZTBBpbSdbUmmtCoZ4EGkUG5D+Ivmb71PTKF8MZefmeyJ3ccfQh0KqpRsDEAUzRPOW1UY1oUtkWL1u1s4BxrL6f4Ox7xZ4qe0RgKibEJmXQmfnwLQFhGH0DPkYqp2MMguYJq2GRXPJvOAWbiPDNOMTJz0aduVugzmbZYJ5p9zlFGSOo4iFBjbexRZB9Zpaj/xrBzQN
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

