apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBKlUOpP6QlRazV5/AJ2aIM/ia4vkJEbNbT4looXqSFpP+F+5PlUqabhzYBykpsGzqTMoQrS5zJVj+oYPNM5bW9BNMr5CJ1pPaNixwGbt3OWlG9fQzDS6WVHPwVyw1gilgXdmMD+h6GKUai0mrI2u6s+Uzj2GX4ha4LhzU6qX6XmbEFQ2jiRFdWcvEvlTmX4kdFuQlLfz+G4H1HXVgTzw/xWSREfmyOoa2MXd1LCkMHaaowazX+OEJ5+gzBms/60/1OuQD+pdSk/RHy5dGUt1pAi6tEVQgq+Nx1l9pgYKN3ueCE9lkAPDVCqaeydi5RHxK5lAwlbyyi7eGf6W4VpvFzcN35QuQFCHSZqbyZXGDaMLw9etROHZHW2qcVBhr4Ezi7iL8xtrFsWD1Kp5hxPvfGVk+kM3Dot05bqqEgIk+1qd8oeBSwQmv/8qQ21Ceql9E+dR7E1LlRZLvYJoDMlaVNQA5NX1S8ncZV8LJisgxTZd6OUa7RgFq0Lx7zA5k9e52qjOBG44mjA3PNlN+xKHDt2kcCcQLPogYfAGc9Utaz/Z8mauXRvCoPalF9BxT4emXN1vp00Mlb85G36FdbKqaQmonURe/WxaRmEPduE4Et65JL5BgSqLTDcxaKUeFUlHZU5b7pf7Yx16pUVJfLvzVKImhAGm6VzM/HH2Go2+/3E6FJT9kGXHDo+LOM/DD3yvYYhbNZhFkodeEmKUBBGsDQO0G9WdlDUBg4jvJg4bB6MCK8sQ6SNIS0
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

