apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCIW5P3L9y8VZh/vP7hx/uKGtfvCXk0peKmfzn2c1BoupyCzwVrXxefIZvtccBbfV59j21lP2ac7pIbVbu2GFTYutW4oNl6mGbo4T3LsCQDngkRoquC3m5lt4BUOtFnCtr8BnnL7jhGdZP/jD94zNhKCuSlTEpStAt/7jFzZbiyqGMW5fTl0DrbPtMD4R3WeJSPBHsKv/dehq6ch1MHoZn6ZldlGTW38fnMdptR9gt6MXMwOy+t6FC55SgKBhy3QK6vpIR39860zHXIs+R2sQwvRs+cTkgPbcCUu2tWOzJT0pt6hT5UaWlpd4r1D2sI+aZD4oMXVsZw1pG2wOtUPnlimahwStqFPfu/hFGGIUsZu52Yf9+uhhA4MyVu3oMLf9J38yZ5tsCm31JBCS3W0gFYbANbkIhhSFJtqn4z6CU8gttnAOq0iMKxewSoYKAv0p7RMPUF/ILn5BVpALntcn7AElLYqFvzxzks4LFKpXHNfQ2GMWpNS0K4h1LFLMG2RPA0LVhpNbqAun52OPxMFUtZasu+Y9iVeCECDxdNNLmMBVQyGHjD3yguQ1AW1yGe6ts49KBZGmt05FTH/ecL77swQhFzx3qRG1HWkqD+vVoqNC47xRRAoFKh/V/ER8CDKe3i4AeYhfZdJoE9m1/Uugu7DHkpEGmlkClLtElBN/p08b9i4LmQWnzBfvrb8q3DNIH76gXRMeoIPQIWKJPn/VqURhNbGaVbEJO60K2ss9a2M7NgxKmkQKf/
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

